import { NextResponse } from 'next/server'
import { cookies } from 'next/headers'
import { eq } from 'drizzle-orm'
import { db } from '@/server/db/client'
import { sessions, users } from '@/server/db/schema'
import { clientKey, rateLimit } from '@/lib/rate-limit'

// Dev-only sign-in. Guarded by:
//   1. NODE_ENV must NOT be 'production'
//   2. email must appear in DEV_BYPASS_EMAILS (comma-separated env var,
//      defaults to "test@gmail.com")
// Creates the user on first use, mints a session row + cookie that
// matches Auth.js's database-session format so auth() picks it up.
function bypassList(): string[] {
  const raw = process.env.DEV_BYPASS_EMAILS ?? 'test@gmail.com'
  return raw.split(',').map((s) => s.trim().toLowerCase()).filter(Boolean)
}

export async function POST(req: Request) {
  // Disabled in prod UNLESS the operator explicitly opts in with
  // ALLOW_DEV_SIGNIN=true. Keep that off the moment Google OAuth is wired.
  const allowed = process.env.NODE_ENV !== 'production' || process.env.ALLOW_DEV_SIGNIN === 'true'
  if (!allowed) {
    return NextResponse.json({ error: 'Disabled in production' }, { status: 403 })
  }
  // 10 attempts / minute per IP — generous for legit dev use, harsh enough
  // to make brute-force discovery of allow-listed emails uninteresting.
  if (!rateLimit(clientKey(req, 'dev-signin'), 10, 60_000)) {
    return NextResponse.json({ error: 'Too many requests' }, { status: 429 })
  }
  const { email: rawEmail } = (await req.json().catch(() => ({}))) as { email?: string }
  const email = String(rawEmail ?? '').toLowerCase().trim()
  if (!email || !bypassList().includes(email)) {
    return NextResponse.json({ error: 'Email not on dev allowlist' }, { status: 403 })
  }

  // Upsert the user. UUID is generated by the schema default if new.
  let row = (await db.select().from(users).where(eq(users.email, email)))[0]
  if (!row) {
    await db.insert(users).values({ email, name: 'Dev User', emailVerified: new Date() })
    row = (await db.select().from(users).where(eq(users.email, email)))[0]!
  }

  // Mint a session that DrizzleAdapter will recognize.
  const token = crypto.randomUUID()
  const expires = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000)
  await db.insert(sessions).values({ sessionToken: token, userId: row.id, expires })

  const jar = await cookies()
  jar.set({
    name: 'authjs.session-token',
    value: token,
    httpOnly: true,
    sameSite: 'lax',
    expires,
    path: '/',
  })
  return NextResponse.json({ ok: true, redirect: '/dashboard' })
}
