import { describe, it, expect, beforeAll } from 'vitest'
import Database from 'better-sqlite3'
import { drizzle } from 'drizzle-orm/better-sqlite3'
import { migrate } from 'drizzle-orm/better-sqlite3/migrator'
import { and, eq } from 'drizzle-orm'
import path from 'node:path'
import * as schema from '@/server/db/schema'

// Fresh in-memory SQLite per test file → hermetic. We run the real migrations
// generated by drizzle-kit so the assertions exercise the production schema.
const sqlite = new Database(':memory:')
sqlite.pragma('foreign_keys = ON')
const db = drizzle(sqlite, { schema })

beforeAll(() => {
  migrate(db, { migrationsFolder: path.join(process.cwd(), 'server/db/migrations') })
})

async function makeUser(email: string): Promise<string> {
  const id = crypto.randomUUID()
  await db.insert(schema.users).values({ id, email })
  return id
}

describe('multi-tenant isolation', () => {
  it('user A cannot read user B contacts via the same WHERE', async () => {
    const a = await makeUser(`a-${crypto.randomUUID()}@x.co`)
    const b = await makeUser(`b-${crypto.randomUUID()}@x.co`)
    await db.insert(schema.contacts).values({ userId: a, recruiterEmail: 'aa@x.co', company: 'A Co' })
    await db.insert(schema.contacts).values({ userId: b, recruiterEmail: 'bb@x.co', company: 'B Co' })
    const seenByA = await db.select().from(schema.contacts).where(eq(schema.contacts.userId, a))
    const seenByB = await db.select().from(schema.contacts).where(eq(schema.contacts.userId, b))
    expect(seenByA.map((r) => r.recruiterEmail)).toEqual(['aa@x.co'])
    expect(seenByB.map((r) => r.recruiterEmail)).toEqual(['bb@x.co'])
  })

  it('deleting user A cascades and leaves user B intact', async () => {
    const a = await makeUser(`del-${crypto.randomUUID()}@x.co`)
    const b = await makeUser(`keep-${crypto.randomUUID()}@x.co`)
    await db.insert(schema.contacts).values({ userId: a, recruiterEmail: 'a1@x.co' })
    await db.insert(schema.contacts).values({ userId: a, recruiterEmail: 'a2@x.co' })
    await db.insert(schema.contacts).values({ userId: b, recruiterEmail: 'b1@x.co' })
    await db.delete(schema.users).where(eq(schema.users.id, a))
    // Scoped to JUST the users created in this test (the file shares one DB
    // across tests, so we can't assert on the whole table).
    const aLeft = await db.select().from(schema.contacts).where(eq(schema.contacts.userId, a))
    const bLeft = await db.select().from(schema.contacts).where(eq(schema.contacts.userId, b))
    expect(aLeft).toHaveLength(0)            // cascade wiped a's contacts
    expect(bLeft.map((r) => r.recruiterEmail)).toEqual(['b1@x.co'])
  })

  it('events row is scoped by user and indexable by kind+ts', async () => {
    const a = await makeUser(`ev-${crypto.randomUUID()}@x.co`)
    const t = Date.now()
    await db.insert(schema.events).values({ userId: a, kind: 'sent', ts: t })
    await db.insert(schema.events).values({ userId: a, kind: 'open', ts: t + 1 })
    const sent = await db.select().from(schema.events)
      .where(and(eq(schema.events.userId, a), eq(schema.events.kind, 'sent')))
    expect(sent).toHaveLength(1)
  })
})
