import { NextResponse } from 'next/server'
import { cookies } from 'next/headers'
import { eq } from 'drizzle-orm'
import { db } from '@/server/db/client'
import { auditLog, sessions, users } from '@/server/db/schema'
import { clientKey, rateLimit } from '@/lib/rate-limit'
import { sessionCookieAttrs } from '@/lib/cookies'

// Sanitize the email-ish value the attacker controls before it lands in
// the audit detail. Without this, a payload like
//   email='victim@example.com reason=success granted=admin'
// would let an attacker forge log fields that confuse admins skimming
// /audit. We keep only [a-z0-9.@_+-] and clamp to 120 chars.
function safeEmail(raw: string): string {
  return raw.toLowerCase().replace(/[^a-z0-9.@_+\-]/g, '').slice(0, 120)
}

// Best-effort audit row for failed sign-in attempts. Surfaces at
// /audit?scope=all so admins can spot probing patterns.
async function logSignInFailure(reason: string, ip: string, email: string) {
  try {
    // Detail is structured as `reason=<safe-keyword>` only. The submitted
    // email goes through safeEmail and lives in a separate quoted field
    // so an attacker can't inject "reason=" into the audit string.
    const detail = email
      ? `reason=${reason} email="${safeEmail(email)}"`
      : `reason=${reason}`
    await db.insert(auditLog).values({
      userId: null, action: 'security.dev_signin_denied',
      detail, ip,
    })
  } catch { /* non-fatal */ }
}

// Dev-only sign-in. Guarded by:
//   1. NODE_ENV must NOT be 'production'
//   2. email must appear in DEV_BYPASS_EMAILS (comma-separated env var,
//      defaults to "test@gmail.com")
// Creates the user on first use, mints a session row + cookie that
// matches Auth.js's database-session format so auth() picks it up.
function bypassList(): string[] {
  const raw = process.env.DEV_BYPASS_EMAILS ?? 'test@gmail.com'
  return raw.split(',').map((s) => s.trim().toLowerCase()).filter(Boolean)
}

export async function POST(req: Request) {
  const ip = (req.headers.get('x-forwarded-for')?.split(',')[0]?.trim()
    || req.headers.get('x-real-ip')
    || 'anon')
  // Disabled in prod UNLESS the operator explicitly opts in with
  // ALLOW_DEV_SIGNIN=true. Keep that off the moment Google OAuth is wired.
  const allowed = process.env.NODE_ENV !== 'production' || process.env.ALLOW_DEV_SIGNIN === 'true'
  if (!allowed) {
    void logSignInFailure('disabled_in_prod', ip, '')
    return NextResponse.json({ error: 'Disabled in production' }, { status: 403 })
  }
  // 10 attempts / minute per IP — generous for legit dev use, harsh enough
  // to make brute-force discovery of allow-listed emails uninteresting.
  if (!rateLimit(clientKey(req, 'dev-signin'), 10, 60_000)) {
    void logSignInFailure('rate_limited', ip, '')
    return NextResponse.json({ error: 'Too many requests' }, { status: 429 })
  }
  const { email: rawEmail } = (await req.json().catch(() => ({}))) as { email?: string }
  const email = String(rawEmail ?? '').toLowerCase().trim()
  if (!email || !bypassList().includes(email)) {
    void logSignInFailure('not_allowlisted', ip, email)
    return NextResponse.json({ error: 'Email not on dev allowlist' }, { status: 403 })
  }

  // Upsert the user. UUID is generated by the schema default if new.
  let row = (await db.select().from(users).where(eq(users.email, email)))[0]
  if (!row) {
    await db.insert(users).values({ email, name: 'Dev User', emailVerified: new Date() })
    row = (await db.select().from(users).where(eq(users.email, email)))[0]!
  }

  // Mint a session that DrizzleAdapter will recognize.
  const token = crypto.randomUUID()
  const expires = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000)
  await db.insert(sessions).values({ sessionToken: token, userId: row.id, expires })

  const jar = await cookies()
  jar.set({ name: 'authjs.session-token', value: token, ...sessionCookieAttrs(), expires })
  return NextResponse.json({ ok: true, redirect: '/dashboard' })
}
